# Generated by Django 3.0 on 2021-08-02 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='Modify Date')),
                ('job_id', models.BigIntegerField(unique=True)),
                ('job_description', models.CharField(blank=True, max_length=255, null=True)),
                ('client_id', models.BigIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_job', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'db_table': 'job',
            },
        ),
        migrations.CreateModel(
            name='RoomColorChoiceModelMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='Modify Date')),
                ('color', models.CharField(max_length=20)),
                ('flat', models.BooleanField(default=False)),
                ('round', models.BooleanField(default=False)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='color_pics')),
            ],
            options={
                'verbose_name': 'Room Color Choice Map',
                'verbose_name_plural': 'Room Color Choices Map',
                'db_table': 'room_colors_choice_map',
            },
        ),
        migrations.CreateModel(
            name='RoomEdgeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='Modify Date')),
                ('edge_type_code', models.BigIntegerField()),
                ('edge_type_text', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Room Edge Type Map',
                'verbose_name_plural': 'Room Edge Types Map',
                'db_table': 'room_edge_type_map',
            },
        ),
        migrations.CreateModel(
            name='RoomMatTypeModelMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='Modify Date')),
                ('mat_code', models.BigIntegerField()),
                ('mat_description', models.TextField(max_length=255)),
            ],
            options={
                'verbose_name': 'Room Material Type Map',
                'verbose_name_plural': 'Room Material Types Map',
                'db_table': 'room_material_type_map',
            },
        ),
        migrations.CreateModel(
            name='RoomProfileModelMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='Modify Date')),
                ('profile_code', models.BigIntegerField()),
                ('profile_text', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Room Profile Map',
                'verbose_name_plural': 'Room Profiles Map',
                'db_table': 'room_profile_map',
            },
        ),
        migrations.CreateModel(
            name='RoomModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='Modify Date')),
                ('room_name', models.CharField(max_length=255)),
                ('room_key', models.CharField(blank=True, max_length=255, null=True)),
                ('bd_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_bd_color', to='franchise.RoomColorChoiceModelMap')),
                ('dd_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_dd_color', to='franchise.RoomColorChoiceModelMap')),
                ('dd_ed_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_dd_ed_color', to='franchise.RoomColorChoiceModelMap')),
                ('dd_ed_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_dd_ed_profile', to='franchise.RoomProfileModelMap')),
                ('dd_ed_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_dd_ed_type', to='franchise.RoomEdgeType')),
                ('dd_mat_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_dd_mat_type', to='franchise.RoomMatTypeModelMap')),
                ('ed_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_ed_color', to='franchise.RoomColorChoiceModelMap')),
                ('ed_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_ed_profile', to='franchise.RoomProfileModelMap')),
                ('ed_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_ed_type', to='franchise.RoomEdgeType')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_room', to='franchise.JobModel')),
                ('mat_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_mat_type', to='franchise.RoomMatTypeModelMap')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'db_table': 'room',
            },
        ),
        migrations.AddField(
            model_name='roomcolorchoicemodelmap',
            name='mat_type',
            field=models.ManyToManyField(related_name='mat_type_color', to='franchise.RoomMatTypeModelMap'),
        ),
    ]
