# Generated by Django 3.0 on 2021-08-07 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franchise', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomcolorchoicemodelmap',
            name='color',
            field=models.CharField(max_length=400),
        ),
    ]
