# Generated by Django 3.0 on 2021-08-07 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('franchise', '0002_auto_20210807_1811'),
        ('franchise', '0002_jobmodel_status'),
    ]

    operations = [
    ]
