# Generated by Django 3.0 on 2021-08-02 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('franchise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoorDrillMapModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='Modify Date')),
                ('drill_id', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Door Dill OPtion',
                'verbose_name_plural': 'Door Dill OPtions Map',
                'db_table': 'door_drill_option',
            },
        ),
        migrations.CreateModel(
            name='DoorOpeningSizeMapModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='Modify Date')),
                ('opening_size', models.IntegerField()),
                ('text', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Door Openings size',
                'verbose_name_plural': 'Door Openings size Map ',
                'db_table': 'door_openings_size',
            },
        ),
        migrations.CreateModel(
            name='DoorSingleOpeningSizeMapModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='Modify Date')),
                ('opening_size', models.IntegerField()),
                ('text', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Door Single Openings size',
                'verbose_name_plural': 'Door Single  Openings size Map ',
                'db_table': 'door_single_openings_size',
            },
        ),
        migrations.CreateModel(
            name='DrawerSizeMapModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='Modify Date')),
                ('height', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Height')),
                ('standard_size', models.CharField(max_length=3)),
            ],
            options={
                'verbose_name': 'Drawer Size OPtion',
                'verbose_name_plural': 'Drawer Size OPtions ',
                'db_table': 'drawer_size_option',
            },
        ),
        migrations.CreateModel(
            name='RoomDescriptionMapModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='Modify Date')),
                ('desc_id', models.BigIntegerField()),
                ('desc_text', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Room Description Map',
                'verbose_name_plural': 'Room Descriptions Map',
                'db_table': 'room_description_map',
            },
        ),
        migrations.CreateModel(
            name='RoomDrillModelMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='Modify Date')),
                ('drill_code', models.BigIntegerField(verbose_name='DrillCode')),
                ('description', models.CharField(max_length=255)),
                ('part_category', models.BigIntegerField(blank=True, null=True, verbose_name='Part Category')),
                ('height', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Height')),
                ('width', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Width')),
                ('depth', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Depth')),
                ('hole_size', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Hole Size')),
                ('pps_uom', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Price Per Sales UOM')),
            ],
            options={
                'verbose_name': 'Room Drill Option',
                'verbose_name_plural': 'Room Drill Options',
                'db_table': 'room_drill_map',
            },
        ),
        migrations.CreateModel(
            name='RoomOptionsMasterModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='Modify Date')),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='Description')),
                ('description2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description2')),
                ('UOM', models.CharField(blank=True, max_length=15, null=True, verbose_name='UOM')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('depth', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('quantity', models.BigIntegerField(blank=True, null=True, verbose_name='Quantity')),
                ('holes', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Holes')),
                ('drill_pattern_height', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('drill_pattern_width', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('drill_pattern_depth', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('drill_pattern_left', models.BooleanField(blank=True, default=False, null=True)),
                ('drill_pattern_right', models.BooleanField(blank=True, default=False, null=True)),
                ('left_side_drill_depth', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('left_side_drill_height', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('right_side_drill_depth', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('right_side_drill_height', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('mat_type', models.SmallIntegerField(blank=True, choices=[(1, 'Mel'), (2, 'P/B')], null=True)),
                ('part_sub_category', models.CharField(blank=True, max_length=20, null=True)),
                ('edge_profile', models.SmallIntegerField(blank=True, choices=[(1, 'Flat'), (2, 'Round')], null=True)),
                ('left_3rd_line_hole', models.BooleanField(blank=True, null=True)),
                ('right_3rd_line_hole', models.BooleanField(blank=True, null=True)),
                ('dog_eared', models.SmallIntegerField(blank=True, choices=[(1, 'No Dogear'), (2, 'Dog Eared to 12"'), (3, 'Dog Eared to 16"')], null=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True, verbose_name='notes')),
                ('door_class_insert', models.BooleanField(blank=True, default=False, null=True)),
                ('door_drill_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='door_drill_optoins', to='room_options.DoorDrillMapModel')),
                ('door_opening_size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='door_openigs', to='room_options.DoorOpeningSizeMapModel')),
                ('door_single_opening_size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='door_single_openigs', to='room_options.DoorSingleOpeningSizeMapModel')),
                ('ed_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_option_ed_type', to='franchise.RoomEdgeType')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_room_option', to='franchise.RoomModel')),
            ],
            options={
                'verbose_name': 'Room Option Master',
                'verbose_name_plural': 'Room Options Master',
                'db_table': 'room_options_master',
            },
        ),
        migrations.CreateModel(
            name='DoorSingleOpeningheightWidthMapModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='Modify Date')),
                ('height', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Height')),
                ('width', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Width')),
                ('depth', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Depth')),
                ('is_active', models.BooleanField(default=True)),
                ('opening_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='door_opening_size', to='room_options.DoorSingleOpeningSizeMapModel')),
            ],
            options={
                'verbose_name': 'Door Single Openings Height & width',
                'verbose_name_plural': 'Door Single Openings Height & width Map ',
                'db_table': 'door_single_openings_height_width_map',
            },
        ),
        migrations.CreateModel(
            name='DoorOpeningheightWidthMapModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='Modify Date')),
                ('height', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Height')),
                ('width', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Width')),
                ('holes', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Holes')),
                ('depth', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Depth')),
                ('is_active', models.BooleanField(default=True)),
                ('opening_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='door_opening_size', to='room_options.DoorOpeningSizeMapModel')),
            ],
            options={
                'verbose_name': 'Door Openings Height & width',
                'verbose_name_plural': 'Door Openings Height & width Map ',
                'db_table': 'door_openings_height_width_map',
            },
        ),
    ]
