# Generated by Django 3.0 on 2021-08-03 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room_options', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KdDepth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='Modify Date')),
                ('kd_depth', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('kd_depth_text', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Kd Depth',
                'verbose_name_plural': 'Kd Depth',
                'db_table': 'kd_depth',
            },
        ),
        migrations.CreateModel(
            name='KdEdge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='Modify Date')),
                ('kd_edge', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('kd_edge_text', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Kd Shelf Edge',
                'verbose_name_plural': 'Kd Edge',
                'db_table': 'kd_edge',
            },
        ),
        migrations.CreateModel(
            name='KdInsertBacking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='Modify Date')),
                ('kd_backing_size', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('kd_backing_text', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Kd Insert backing',
                'verbose_name_plural': 'Kd Insert backing',
                'db_table': 'kd__insert_backing',
            },
        ),
        migrations.CreateModel(
            name='KdMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='Modify Date')),
                ('kd_material', models.BigIntegerField()),
                ('kd_material_text', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Kd Material',
                'verbose_name_plural': 'Kd Material',
                'db_table': 'kd_material',
            },
        ),
        migrations.CreateModel(
            name='KdWidth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='Modify Date')),
                ('kd_width', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('kd_width_text', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Kd Width',
                'verbose_name_plural': 'Kd Width',
                'db_table': 'kd_width',
            },
        ),
        migrations.AddField(
            model_name='roomoptionsmastermodel',
            name='kd_shelf_depth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kd_shelf_depth', to='room_options.KdDepth'),
        ),
        migrations.AddField(
            model_name='roomoptionsmastermodel',
            name='kd_shelf_edge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kd_shelf_edge', to='room_options.KdEdge'),
        ),
        migrations.AddField(
            model_name='roomoptionsmastermodel',
            name='kd_shelf_insert_backing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kd_shelf_insert_backing', to='room_options.KdInsertBacking'),
        ),
        migrations.AddField(
            model_name='roomoptionsmastermodel',
            name='kd_shelf_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kd_shelf_material', to='room_options.KdMaterial'),
        ),
        migrations.AddField(
            model_name='roomoptionsmastermodel',
            name='kd_shelf_width',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kd_shelf_width', to='room_options.KdWidth'),
        ),
    ]
