# Generated by Django 3.0 on 2021-08-03 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_options', '0002_auto_20210803_0640'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomoptionsmastermodel',
            name='cleat_exposed_ends',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('single', 'Single Exposed Ends'), ('both', 'Both Exposed Ends'), ('edgeband', 'Edgeband All 4 sizes (Robe Hook Cleat)')], max_length=20, null=True),
        ),
    ]
