# Generated by Django 3.0 on 2021-08-05 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room_options', '0003_roomoptionsmastermodel_cleat_exposed_ends'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kdinsertbacking',
            options={'verbose_name': 'Kd Shelf Insert backing', 'verbose_name_plural': 'Kd Shelf Insert backing'},
        ),
        migrations.RenameField(
            model_name='roomoptionsmastermodel',
            old_name='kd_shelf_insert_backing',
            new_name='insert_backing',
        ),
        migrations.RemoveField(
            model_name='roomoptionsmastermodel',
            name='kd_shelf_depth',
        ),
        migrations.RemoveField(
            model_name='roomoptionsmastermodel',
            name='kd_shelf_edge',
        ),
        migrations.RemoveField(
            model_name='roomoptionsmastermodel',
            name='kd_shelf_material',
        ),
        migrations.RemoveField(
            model_name='roomoptionsmastermodel',
            name='kd_shelf_width',
        ),
        migrations.AlterModelTable(
            name='kdinsertbacking',
            table='kd_shelf_insert_backing',
        ),
    ]
