# Generated by Django 3.0 on 2021-08-04 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_options', '0003_roomoptionsmastermodel_cleat_exposed_ends'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomoptionsmastermodel',
            name='depth2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='roomoptionsmastermodel',
            name='drill_toe_kick',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='roomoptionsmastermodel',
            name='notch_mitered_pard',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='roomoptionsmastermodel',
            name='shelf_type',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Adj.'), (2, 'KD')], null=True),
        ),
        migrations.AddField(
            model_name='roomoptionsmastermodel',
            name='shelfs_partitions',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Sq')], null=True),
        ),
        migrations.AddField(
            model_name='roomoptionsmastermodel',
            name='width2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
