# Generated by Django 3.0 on 2021-08-05 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room_options', '0004_auto_20210805_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomoptionsmastermodel',
            name='kd_shelf_edge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kd_shelf_edge', to='room_options.KdEdge'),
        ),
    ]
