# Generated by Django 3.0 on 2021-08-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_options', '0004_auto_20210804_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomoptionsmastermodel',
            name='exposed_ends',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('single', 'Single Exposed Ends'), ('both', 'Both Exposed Ends')], max_length=20, null=True),
        ),
    ]
