# Generated by Django 3.0 on 2021-08-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_options', '0005_roomoptionsmastermodel_kd_shelf_edge'),
    ]

    operations = [
        migrations.AddField(
            model_name='kddepth',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='kdedge',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='kdinsertbacking',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='kdmaterial',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='kdwidth',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
