# Generated by Django 3.0 on 2021-08-05 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room_options', '0006_auto_20210805_1024'),
        ('room_options', '0004_auto_20210804_1335'),
    ]

    operations = [
    ]
