# Generated by Django 3.0 on 2021-08-05 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room_options', '0005_roomoptionsmastermodel_exposed_ends'),
        ('room_options', '0007_merge_20210805_1831'),
    ]

    operations = [
    ]
