# Generated by Django 3.0 on 2021-08-06 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_options', '0008_merge_20210805_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdjEdge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='Modify Date')),
                ('adj_edge', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('adj_edge_text', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Adj Shelf Edge',
                'verbose_name_plural': 'Adj Edge',
                'db_table': 'adj_edge',
            },
        ),
        migrations.CreateModel(
            name='AdjInsertBacking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='Modify Date')),
                ('adj_backing_size', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('adj_backing_text', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Adj Shelf Insert backing',
                'verbose_name_plural': 'Adj Shelf Insert backing',
                'db_table': 'adj_shelf_insert_backing',
            },
        ),
        migrations.CreateModel(
            name='AdjMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='Modify Date')),
                ('adj_material', models.BigIntegerField()),
                ('adj_material_text', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Adj Material',
                'verbose_name_plural': 'Adj Material',
                'db_table': 'adj_material',
            },
        ),
        migrations.CreateModel(
            name='AdjWidth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='Modify Date')),
                ('adj_width', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('adj_width_text', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Adj Width',
                'verbose_name_plural': 'Adj Width',
                'db_table': 'adj_width',
            },
        ),
        migrations.CreateModel(
            name='AjdDepth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='Modify Date')),
                ('adj_depth', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('adj_depth_text', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Adj Depth',
                'verbose_name_plural': 'Adj Depth',
                'db_table': 'adj_depth',
            },
        ),
    ]
