# Generated by Django 3.0 on 2021-08-06 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room_options', '0008_merge_20210805_1945'),
        ('room_options', '0007_merge_20210805_1246'),
    ]

    operations = [
    ]
