# Generated by Django 3.0 on 2021-08-06 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_options', '0009_merge_20210806_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomoptionsmastermodel',
            name='end_caps',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='roomoptionsmastermodel',
            name='face_color',
            field=models.CharField(blank=True, choices=[('main', 'Main'), ('door n drawer', "Door'' n Drawer")], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='roomoptionsmastermodel',
            name='plywood',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='roomoptionsmastermodel',
            name='toe_kick_depth',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
