# Generated by Django 3.0 on 2021-08-06 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_options', '0010_auto_20210806_0654'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomoptionsmastermodel',
            name='drawer_faces_drill_Sub_front',
            field=models.CharField(blank=True, choices=[(1, 'No Drill'), (2, 'pull 76 mm'), (3, 'pull 96 mm'), (4, 'pull 76 mm'), (5, 'pull 96 mm')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='roomoptionsmastermodel',
            name='drawer_faces_hamper_faces',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='roomoptionsmastermodel',
            name='drawer_faces_hamper_type',
            field=models.CharField(blank=True, choices=[(1, '18H (22.52)'), (2, '19H (23.78)')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='roomoptionsmastermodel',
            name='drawer_faces_holes',
            field=models.CharField(blank=True, choices=[(3, '3 Hole (3.62")'), (4, '4 Hole (4.88")'), (5, '5 Hole (6.14")'), (6, '6 Hole (7.40")'), (7, '7 Hole (8.66")'), (8, '8 Hole (9.92")'), (9, '9 Hole (11.18")'), (10, '10 Hole (12.44")')], max_length=20, null=True),
        ),
    ]
