# Generated by Django 3.0 on 2021-08-06 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_options', '0012_auto_20210806_0727'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdjExposedEnd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='Modify Date')),
                ('end_code', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('end_code_text', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Adj Exposed End',
                'verbose_name_plural': 'Adj Exposed End',
                'db_table': 'adj_exposed_end',
            },
        ),
    ]
