# Generated by Django 3.0 on 2021-08-06 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room_options', '0013_adjexposedend'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomoptionsmastermodel',
            name='adj_exposed_end',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adj_exposed_end', to='room_options.AdjExposedEnd'),
        ),
    ]
