# Generated by Django 3.0 on 2021-08-06 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room_options', '0014_roomoptionsmastermodel_adj_exposed_end'),
        ('room_options', '0010_auto_20210806_0654'),
    ]

    operations = [
    ]
