# Generated by Django 3.0 on 2021-08-06 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room_options', '0011_auto_20210806_1622'),
        ('room_options', '0015_merge_20210806_2048'),
    ]

    operations = [
    ]
