# Generated by Django 3.0 on 2021-08-07 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_options', '0016_merge_20210806_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomoptionsmastermodel',
            name='drawer_faces_drill_Sub_front',
            field=models.CharField(blank=True, choices=[('No Drill', 'No Drill'), ('pull 76 mm', 'pull 76 mm'), ('pull 96 mm', 'pull 96 mm'), ('pull 128 mm', 'pull 128 mm'), ('Knob', 'Knob'), ('Custom', 'Custom')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='roomoptionsmastermodel',
            name='drawer_faces_hamper_type',
            field=models.CharField(blank=True, choices=[('18H (22.52)', '18H (22.52)'), ('19H (23.78)', '19H (23.78)')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='roomoptionsmastermodel',
            name='drawer_faces_holes',
            field=models.CharField(blank=True, choices=[('3 Hole (3.62")', '3 Hole (3.62")'), ('4 Hole (4.88")', '4 Hole (4.88")'), ('5 Hole (6.14")', '5 Hole (6.14")'), ('6 Hole (7.40")', '6 Hole (7.40")'), ('7 Hole (8.66")', '7 Hole (8.66")'), ('8 Hole (9.92")', '8 Hole (9.92")'), ('9 Hole (11.18")', '9 Hole (11.18")'), ('10 Hole (12.44")', '10 Hole (12.44")')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='roomoptionsmastermodel',
            name='face_color',
            field=models.CharField(blank=True, choices=[('main', 'Main'), ('doorndrawer', "Door'' n Drawer")], max_length=20, null=True),
        ),
    ]
